import React, { createContext, useContext, useState } from 'react';

const en: Record<string, string> = {
  appName: 'RythuLink', tagline: 'Connecting Farmers Directly to Shops',
  loginWithGoogle: 'Continue with Google', selectRole: 'Select Your Role',
  iAmFarmer: "I'm a Farmer", iAmBuyer: "I'm a Buyer",
  shopOwner: 'Shop Owner', restaurant: 'Restaurant', bulkBuyer: 'Bulk Buyer',
  completeProfile: 'Complete Your Profile', saveAndContinue: 'Save & Continue',
  home: 'Home', orders: 'Orders', prices: 'Prices', profile: 'Profile',
  marketplace: 'Marketplace', needs: 'Buyer Needs', postNeed: 'Post Need',
  postCrop: 'Post Crop', myListings: 'My Listings',
  goodDay: 'Good day', activeListings: 'Active Listings', totalOrders: 'Total Orders',
  revenue: 'Revenue', rating: 'Rating', pendingOrders: 'pending orders',
  browseMarketplace: 'Browse Marketplace', postANeed: 'Post a Need',
  recentListings: 'Recent Listings', recentOrders: 'Recent Orders', seeAll: 'See all →',
  cropName: 'Crop Name', quantity: 'Quantity (kg)', price: 'Price / kg (₹)',
  variety: 'Variety', district: 'District', description: 'Description',
  uploadImage: 'Upload Crop Photo', postListing: 'Post Listing',
  orderNow: 'Order Now', acceptNeed: 'Accept This Need',
  myNeeds: 'My Needs', postNeedForm: 'Post a Crop Need',
  maxPrice: 'Max Price / kg (₹)', notes: 'Notes',
  pending: 'Pending', confirmed: 'Confirmed', packed: 'Packed',
  outForDelivery: 'Out for Delivery', delivered: 'Delivered', cancelled: 'Cancelled',
  markConfirmed: 'Mark Confirmed', markPacked: 'Mark Packed',
  markShipped: 'Mark Shipped', markDelivered: 'Mark Delivered',
  contactFarmer: 'Contact Farmer', contactBuyer: 'Contact Buyer',
  contactRevealed: 'Contact revealed after order confirmed',
  language: 'Language', logout: 'Logout', editProfile: 'Edit Profile',
  farmerDetails: 'Farmer Details', buyerDetails: 'Buyer Details',
  village: 'Village', mandal: 'Mandal', landArea: 'Land Area (acres)',
  businessName: 'Business Name', businessAddress: 'Business Address', pincode: 'Pincode',
  phone: 'Phone Number', name: 'Full Name', loading: 'Loading...',
  totalValue: 'Total value estimate', uploading: 'Uploading...',
  listingPosted: 'Listing Posted!', needPosted: 'Need Posted!',
  noListings: 'No listings yet', noOrders: 'No orders yet', noNeeds: 'No needs posted',
  shopDetails: 'Shop', restaurantDetails: 'Restaurant', bulkDetails: 'Bulk Buyer',
  filterByDistrict: 'All Districts', search: 'Search crops...',
  buyerNeedsFeed: "Buyer Needs Feed", farmersListings: "Farmer Listings",
  orderPlaced: 'Order placed successfully!', needAccepted: 'Need accepted!',
};

const hi: Record<string, string> = {
  appName: 'रायतुलिंक', tagline: 'किसानों को सीधे दुकानों से जोड़ना',
  loginWithGoogle: 'Google से जारी रखें', selectRole: 'अपनी भूमिका चुनें',
  iAmFarmer: 'मैं किसान हूं', iAmBuyer: 'मैं खरीदार हूं',
  shopOwner: 'दुकानदार', restaurant: 'रेस्टोरेंट', bulkBuyer: 'थोक खरीदार',
  completeProfile: 'प्रोफाइल पूरी करें', saveAndContinue: 'सेव करें',
  home: 'होम', orders: 'ऑर्डर', prices: 'कीमतें', profile: 'प्रोफाइल',
  marketplace: 'बाज़ार', needs: 'जरूरतें', postNeed: 'जरूरत पोस्ट करें',
  postCrop: 'फसल पोस्ट करें', myListings: 'मेरी लिस्टिंग',
  goodDay: 'नमस्ते', activeListings: 'सक्रिय लिस्टिंग', totalOrders: 'कुल ऑर्डर',
  revenue: 'आमदनी', rating: 'रेटिंग', pendingOrders: 'लंबित ऑर्डर',
  browseMarketplace: 'बाज़ार देखें', postANeed: 'जरूरत पोस्ट करें',
  recentListings: 'हाल की लिस्टिंग', recentOrders: 'हाल के ऑर्डर', seeAll: 'सब देखें →',
  cropName: 'फसल का नाम', quantity: 'मात्रा (किलो)', price: 'कीमत / किलो (₹)',
  variety: 'किस्म', district: 'जिला', description: 'विवरण',
  uploadImage: 'फोटो अपलोड करें', postListing: 'लिस्टिंग पोस्ट करें',
  orderNow: 'ऑर्डर करें', acceptNeed: 'जरूरत स्वीकार करें',
  myNeeds: 'मेरी जरूरतें', postNeedForm: 'फसल की जरूरत पोस्ट करें',
  maxPrice: 'अधिकतम कीमत / किलो (₹)', notes: 'नोट्स',
  pending: 'लंबित', confirmed: 'पुष्टि', packed: 'पैक', outForDelivery: 'रास्ते में',
  delivered: 'डिलीवर', cancelled: 'रद्द', markConfirmed: 'पुष्टि करें',
  markPacked: 'पैक करें', markShipped: 'भेजें', markDelivered: 'डिलीवर करें',
  contactFarmer: 'किसान से संपर्क', contactBuyer: 'खरीदार से संपर्क',
  contactRevealed: 'ऑर्डर पुष्टि के बाद संपर्क दिखेगा',
  language: 'भाषा', logout: 'लॉगआउट', editProfile: 'प्रोफाइल संपादित करें',
  farmerDetails: 'किसान विवरण', buyerDetails: 'खरीदार विवरण',
  village: 'गांव', mandal: 'मंडल', landArea: 'भूमि क्षेत्र (एकड़)',
  businessName: 'व्यापार का नाम', businessAddress: 'व्यापार का पता', pincode: 'पिनकोड',
  phone: 'मोबाइल नंबर', name: 'पूरा नाम', loading: 'लोड हो रहा है...',
  totalValue: 'कुल मूल्य अनुमान', uploading: 'अपलोड हो रहा है...',
  listingPosted: 'लिस्टिंग पोस्ट हो गई!', needPosted: 'जरूरत पोस्ट हो गई!',
  noListings: 'कोई लिस्टिंग नहीं', noOrders: 'कोई ऑर्डर नहीं', noNeeds: 'कोई जरूरत नहीं',
  shopDetails: 'दुकान', restaurantDetails: 'रेस्टोरेंट', bulkDetails: 'थोक खरीदार',
  filterByDistrict: 'सभी जिले', search: 'फसल खोजें...',
  buyerNeedsFeed: 'खरीदारों की जरूरतें', farmersListings: 'किसानों की लिस्टिंग',
  orderPlaced: 'ऑर्डर सफलतापूर्वक दिया गया!', needAccepted: 'जरूरत स्वीकार की गई!',
};

const te: Record<string, string> = {
  appName: 'రైతులింక్', tagline: 'రైతులను నేరుగా దుకాణాలకు అనుసంధానించడం',
  loginWithGoogle: 'Google తో కొనసాగించండి', selectRole: 'మీ పాత్రను ఎంచుకోండి',
  iAmFarmer: 'నేను రైతును', iAmBuyer: 'నేను కొనుగోలుదారును',
  shopOwner: 'దుకాణదారు', restaurant: 'రెస్టారెంట్', bulkBuyer: 'బల్క్ కొనుగోలుదారు',
  completeProfile: 'ప్రొఫైల్ పూర్తి చేయండి', saveAndContinue: 'సేవ్ చేయండి',
  home: 'హోమ్', orders: 'ఆర్డర్లు', prices: 'ధరలు', profile: 'ప్రొఫైల్',
  marketplace: 'మార్కెట్', needs: 'అవసరాలు', postNeed: 'అవసరం పోస్ట్',
  postCrop: 'పంట పోస్ట్', myListings: 'నా లిస్టింగ్‌లు',
  goodDay: 'నమస్కారం', activeListings: 'క్రియాశీల లిస్టింగ్‌లు', totalOrders: 'మొత్తం ఆర్డర్లు',
  revenue: 'ఆదాయం', rating: 'రేటింగ్', pendingOrders: 'పెండింగ్ ఆర్డర్లు',
  browseMarketplace: 'మార్కెట్ చూడండి', postANeed: 'అవసరం పోస్ట్ చేయండి',
  recentListings: 'ఇటీవలి లిస్టింగ్‌లు', recentOrders: 'ఇటీవలి ఆర్డర్లు', seeAll: 'అన్నీ చూడండి →',
  cropName: 'పంట పేరు', quantity: 'పరిమాణం (కేజీ)', price: 'ధర / కేజీ (₹)',
  variety: 'రకం', district: 'జిల్లా', description: 'వివరణ',
  uploadImage: 'ఫోటో అప్‌లోడ్ చేయండి', postListing: 'లిస్టింగ్ పోస్ట్ చేయండి',
  orderNow: 'ఆర్డర్ చేయండి', acceptNeed: 'అవసరాన్ని అంగీకరించండి',
  myNeeds: 'నా అవసరాలు', postNeedForm: 'పంట అవసరం పోస్ట్ చేయండి',
  maxPrice: 'గరిష్ట ధర / కేజీ (₹)', notes: 'గమనికలు',
  pending: 'పెండింగ్', confirmed: 'నిర్ధారించబడింది', packed: 'ప్యాక్ చేయబడింది',
  outForDelivery: 'డెలివరీలో', delivered: 'డెలివరీ అయింది', cancelled: 'రద్దు',
  markConfirmed: 'నిర్ధారించండి', markPacked: 'ప్యాక్ చేయండి',
  markShipped: 'పంపండి', markDelivered: 'డెలివరీ చేయండి',
  contactFarmer: 'రైతుని సంప్రదించండి', contactBuyer: 'కొనుగోలుదారుని సంప్రదించండి',
  contactRevealed: 'ఆర్డర్ నిర్ధారణ తర్వాత సంప్రదింపు చూపబడుతుంది',
  language: 'భాష', logout: 'లాగ్ అవుట్', editProfile: 'ప్రొఫైల్ సవరించండి',
  farmerDetails: 'రైతు వివరాలు', buyerDetails: 'కొనుగోలుదారు వివరాలు',
  village: 'గ్రామం', mandal: 'మండలం', landArea: 'భూమి (ఎకరాలు)',
  businessName: 'వ్యాపార పేరు', businessAddress: 'వ్యాపార చిరునామా', pincode: 'పిన్‌కోడ్',
  phone: 'మొబైల్ నంబర్', name: 'పూర్తి పేరు', loading: 'లోడ్ అవుతోంది...',
  totalValue: 'మొత్తం విలువ అంచనా', uploading: 'అప్‌లోడ్ అవుతోంది...',
  listingPosted: 'లిస్టింగ్ పోస్ట్ అయింది!', needPosted: 'అవసరం పోస్ట్ అయింది!',
  noListings: 'లిస్టింగ్‌లు లేవు', noOrders: 'ఆర్డర్లు లేవు', noNeeds: 'అవసరాలు లేవు',
  shopDetails: 'దుకాణం', restaurantDetails: 'రెస్టారెంట్', bulkDetails: 'బల్క్ కొనుగోలుదారు',
  filterByDistrict: 'అన్ని జిల్లాలు', search: 'పంటలు వెతకండి...',
  buyerNeedsFeed: 'కొనుగోలుదారుల అవసరాలు', farmersListings: 'రైతుల లిస్టింగ్‌లు',
  orderPlaced: 'ఆర్డర్ విజయవంతంగా ఇవ్వబడింది!', needAccepted: 'అవసరం అంగీకరించబడింది!',
};

const translations: Record<string, Record<string, string>> = { en, hi, te };

interface LangCtx { lang: string; setLang: (l: string) => void; t: (key: string) => string; }
const LangContext = createContext<LangCtx>(null!);
export const useLanguage = () => useContext(LangContext);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLangState] = useState(localStorage.getItem('rl_lang') || 'en');
  const setLang = (l: string) => { setLangState(l); localStorage.setItem('rl_lang', l); };
  const t = (key: string) => translations[lang]?.[key] || translations.en[key] || key;
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
}
